import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

// The deploy URL is authored in four files and nothing joins them: the README
// twice, the marketing page, and the docs generator, whose output is committed
// and served verbatim. No runtime reads it, so there is nowhere to import it
// from and no build step that would notice a copy going stale.
//
// The failure it guards is silent by construction. A button that lost its
// `products` parameter still renders, still clones, still builds. It just stops
// provisioning a Convex project, and the person who clicked it finds out when
// the deployed page cannot reach a backend. The same is true of a generated
// page rebuilt from an edited source, or not rebuilt at all.
const PARAMS: Record<string, string> = {
  "repository-url": "https://github.com/seonglae/openportfolio",
  "project-name": "openportfolio",
  "repository-name": "openportfolio",
  "demo-title": "openportfolio",
  "demo-description":
    "Every account as one book, every call on the record. One net worth, the investor flows behind the price, and a Brier-scored record of the calls you registered before the fact.",
  "demo-url": "https://openportfolio.app/demo/",
  products: JSON.stringify([
    { type: "integration", integrationSlug: "convex", productSlug: "convex", protocol: "storage" },
  ]),
  // No `env` at all. There was one, VITE_CLERK_PUBLISHABLE_KEY, until sign-in
  // moved to Convex Auth running inside the deployment itself. The import now
  // asks for nothing, which is the strongest form of the claim this file guards.
};

// URLSearchParams writes a space as `+`, which is right for a form body and only
// tolerated in a query string. The authored copies use %20.
const CANONICAL = `https://vercel.com/new/clone?${new URLSearchParams(PARAMS).toString().replace(/\+/g, "%20")}`;

// site/docs/deploy.html is generated by site/build-docs.py and committed, which
// is why it is checked alongside its own source rather than trusted to follow:
// editing the source without running `pnpm site:docs` leaves the served page on
// the previous URL.
const AUTHORED = ["README.md", "site/index.html", "site/build-docs.py", "site/docs/deploy.html"];

const copiesIn = (file: string): string[] => {
  const text = readFileSync(new URL(`../${file}`, import.meta.url), "utf8");
  // The three HTML-bearing files escape the separator; the README does not.
  return (text.match(/https:\/\/vercel\.com\/new\/clone\?[^)"\s]*/g) ?? []).map((url) => url.replace(/&amp;/g, "&"));
};

describe("the deploy button URL", () => {
  for (const file of AUTHORED) {
    it(`is present and canonical in ${file}`, () => {
      const copies = copiesIn(file);
      expect(copies.length, "no deploy button left in this file").toBeGreaterThan(0);
      expect([...new Set(copies)]).toEqual([CANONICAL]);
    });
  }
});

// Byte equality above pins the copies to each other. These pin what the URL has
// to mean, so that editing PARAMS itself cannot quietly undo the thing the
// button exists for.
describe("what the URL has to carry", () => {
  const params = new URL(CANONICAL).searchParams;

  it("provisions the backend through the Convex Marketplace integration", () => {
    expect(JSON.parse(params.get("products") ?? "[]")).toContainEqual(
      expect.objectContaining({ type: "integration", integrationSlug: "convex" }),
    );
  });

  it("asks the user for nothing", () => {
    // Every value this once prompted for has been removed by making the thing
    // that needed it self-hosted: CONVEX_DEPLOY_KEY because the Marketplace
    // integration supplies it, and VITE_CLERK_PUBLISHABLE_KEY because sign-in
    // stopped being someone else's service. An `env` reappearing here means one
    // click quietly became one click plus an errand.
    expect(params.get("env")).toBeNull();
  });

  it("has a deploy docs page to send people to", () => {
    // The URL no longer carries envLink, since Vercel only shows it beside the
    // prompts there are none of. The page it pointed at still has to exist,
    // because the README and the marketing hero both link it.
    const page = readFileSync(new URL("../site/docs/deploy.html", import.meta.url), "utf8");
    expect(page).toContain("convex deploy");
  });
});
